name: mosqguard
description: "Monitor, Prevent, Protect."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2  # For getting the current location
  geocoding: ^2.0.4
  image_picker: ^0.8.7+3
  provider: ^6.1.2
  flutter_svg: ^1.0.0

#  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.14

  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  shared_preferences: ^2.2.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_storage: ^12.4.2
  pinput: ^5.0.1


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mosqguard/Logo-1.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  # Define your assets here so Flutter can use them
  assets:
    - assets/icons/App_Icon.png
    - assets/icons/sri_lanka.png
    - assets/icons/apple-logo.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/guest-icon.png
    - assets/icons/sri-lanka.png
    - assets/icons/default_image_url.png
    - assets/mosqguard/Logo-1.png
    - assets/mosqguard/Logo-2.png
    - assets/mosqguard/Reporting Person.png
    - assets/mosqguard/Logo-3.png
    - assets/mosqguard/status_1.svg
    - assets/mosqguard/status_2.svg
    - assets/mosqguard/status_3.svg
    - assets/mosqguard/status_4.svg