name: mosqguard
description: "Monitor, Prevent, Protect."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  geocoding: ^2.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/App_Icon.png"  # Path to your app icon image

flutter:
  uses-material-design: true

  # Define your assets here so Flutter can use them
  assets:
    - assets/icons/App_Icon.png
    - assets/icons/sri_lanka.png
    - assets/icons/apple-logo.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/sri-lanka.png
    - assets/mosqguard/Logo-1.png
    - assets/mosqguard/Logo-2.png
